### ISSUE TITLE
import cocos.numerics

### ISSUE THREAD

**Issue by Mike-Chester** [michaelnowotny/cocos#2]
Hi, I'm getting an error when I run the following line in the python interpreter or if it is run within a script:
`import cocos.numerics as cn`

This returns the following:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cocos/numerics/__init__.py", line 4, in <module>
    import cocos.numerics.random as random
AttributeError: module 'cocos' has no attribute 'numerics'`

I'm using a Mac (OS X Catalina 10.15.4)
cd.info() does work:
`Cocos running on ArrayFire v3.6.4 (OpenCL 64bit)
[0] Apple: Intel(R) Iris(TM) Plus Graphics 640 | OpenCL | compute version 1.2
`

Thanks
Mike

**Comment by Mike-Chester** [comment]
I managed to resolve this, at least as much as my hardware will allow :)
This is what I did:

- Installed the most recent Python (3.8.3)
- Installed cocos, explicitly calling the newly installed Python: "python3.8 -m pip install cocos"
- Ran the Monte-Carlo test script, again explicitly using the newly installed Python: "python3.8 monte_carlo.py"    

I think the problem was OS Catalina-related. My Intel GPU does not support double precision, but I can get the 'Estimating Pi via Monte-Carlo' example script to work. Output below, just in case anyone is interested in the performance for a 2017, 2.3 GHz i5 MacBook Pro...

simulating 100000000 draws&nbsp;
Estimate of Pi on cpu: 3.1414498 
Estimate of Pi on gpu: 3.14148152 
time elapsed on gpu: 1.0555531978607178 
time elapsed on cpu: 37.267690896987915 
speedup factor on gpu: 35.3063123417352
